config/routes.rb
Innercircle::Application.routes.draw do
  

  resources :contacts
  get 'radar' => 'contacts#radar'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "omniauth_callbacks"}

  authenticated :user do
    root :to => 'contacts#index'
  end

  root :to => 'pages#home'
  get 'about' => 'pages#about'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :name, :email, :phone, :image, :file, :remote_file_url, :file_cache
  mount_uploader :file, FileUploader

  validates :name, presence: true
  validates :email, :presence => true, :email => true
  validates :phone, :presence => true, :phone => true
  validates :file, :presence => true
  validates :user_id, presence: true


  belongs_to :user

  ## Normalizes attribute before validation and saves into other attribute
  #phony_normalize :phone, :default_country_code => 'US'




  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_many :contacts

def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
  end
end

def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
end

def password_required?
  super && provider.blank?
end

def update_with_password(params, *options)
  if encrypted_password.blank?
    update_attributes(params, *options)
  else
    super
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

class String
  def cap_words
    self.split(' ').map {|w| w.capitalize }.join(' ')
  end
end

class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

class PhoneValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not a valid phone number") unless
      value =~ /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_filter :authenticate_user!
  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts
  # GET /contacts.json
  def radar
    @contacts = current_user.contacts.all

    respond_to do |format|
      format.html # radar.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = current_user.contacts.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = current_user.contacts.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = current_user.contacts.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def before_destroy
    
  end


  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    session[:return_to] ||= request.referer
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to session.delete(:return_to) }
      format.json { head :no_content }
    end
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  # alias_method :twitter, :all
  alias_method :google_oauth2, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_contact.html.erb
<tr>
	<td><%= link_to (image_tag contact.file_url(:thumb)), contact %></td>
  <td><%= contact.name.cap_words %></td>
  <td><%= mail_to contact.email, contact.email, :encode => "hex", :target => "_blank" %>
  <td><%= contact.phone.phony_formatted!(:format => :international) %></td>
  <td><%= link_to 'Show', contact %></td>
  <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
  <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact, html: { class: "form-horizontal", :multipart => true }) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_contact_type, class: "alert alert-error" %>


  <%= f.input :name, input_html: { rows: "3" } %>
  <%= f.input :email, input_html: { rows: "3" } %>
  <%= f.input :phone, input_html: { rows: "3" } %>
  <br />
  <%= image_tag(@contact.file_url(:thumb)) if @contact.file? %>
  <%= f.input :file, label: "Upload Image" %>
  <%= f.input :remote_file_url, label: "or input url", input_html: { rows: "3" } %>
  <%= f.hidden_field :file_cache %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div>
  <h1>My Contacts <span class="heading-link">(<%= link_to 'Radar', radar_path %>)</span></h1>
</div>
<div class="well">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Image</th>
        <th>Name</th>
        <th>Email</th>
        <th>Mobile</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @contacts %>
    </tbody>
  </table>
  <%= link_to 'Add New Contact', new_contact_path, class: "btn" %>
</div>
<br />

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/radar.html.erb
<h1>My Contacts <span><%= link_to '(List)', root_path, class: "heading-link" %></span></h1>

<div id="contacts">
	<% @contacts.each do |contact| %>
		<div class="box">
			<%= link_to (image_tag contact.file_url(:radar)), contact %>
			<p class="contact-name">
				<%= contact.name.cap_words %>
			</p>
			<% if current_user == contact.user %>
				<p>
					<%= link_to 'Edit', edit_contact_path(contact) %>
					<%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %>
				</p>
			<% end %>
		</div>
	<% end %>
</div>

app/views/contacts/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @contact.file %>
			<p>
				Name: <%= @contact.name %>
			</p>
			<%= link_to 'Edit', edit_contact_path(@contact) %> |
			<%= link_to 'Back', contacts_path %>
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "About Inner Circle", about_path %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "BASETOUCH", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li><%= link_to "Home", root_path %></li>
		      <li><%= link_to "About", about_path %></li>
      	</ul>
      	<ul class="nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Add +", new_contact_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li> 
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
      	 <% end %>
        </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseTouch.io</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_user_home.html.erb
<h1>You are logged in</h1>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to "One Month Rails", "http://onemonthrails.com" %>
  is a project to teach 
  <%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
  in one month. This is the sample application.
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<%= render 'user_home' %>
<% else %>
	<div class="hero-unit">
		<h1>BaseTouch is</h1>
		<p>
		  Relationship Management for Your Inner Circle.
		</p>
		<p>
		  <%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
		</p>
	</div>
<% end %>